version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Senha do root do MySQL
      MYSQL_DATABASE: estoque           # Banco de dados inicial
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Expondo a porta 3306
    networks:
      - my_network
    restart: always

volumes:
  mysql_data: {}

networks:
  my_network:
    driver: bridge
